use crate::engine::{CONFIG_REPO, LUKS_MAPPER_NAME, ProgressEvent, ProgressSink, Task, TaskCtx};
use crate::mx;
use async_trait::async_trait;

/// File `init` renders and seals immutable; the `imports` list lives here.
const CONFIGURATION_NIX: &str = "configuration.nix";
/// Generated by this task when the root partition is encrypted.
const LUKS_NIX: &str = "luks.nix";
/// Generated by this task when the application pack is not `AppPack::None`.
const APPS_NIX: &str = "apps.nix";

/// Adds to the configuration repository what `modulix_core_utils::init::init`
/// does not know about: the LUKS unlock entry and the application pack.
///
/// Both are new files rather than edits, because `init` seals its own base
/// files immutable (`flake.nix`, `configuration.nix`, `hardware-configuration.nix`,
/// `fstab.nix`, `locale.nix`, `users.nix`). Only `configuration.nix` has to be
/// unsealed, just long enough to extend its `imports` list.
///
/// The LUKS part is not optional polish: without
/// `boot.initrd.luks.devices`, an encrypted install produces a system that
/// cannot find its root device at boot.
pub struct ExtraConfigTask;

#[async_trait]
impl Task for ExtraConfigTask {
    fn label(&self) -> String {
        "Completing the system configuration".to_string()
    }

    fn weight(&self) -> u32 {
        2
    }

    /// # Pre-conditions
    /// `InitConfigTask` has created and committed `CONFIG_REPO`.
    ///
    /// # Post-conditions
    /// Every generated file is imported by `configuration.nix` and committed,
    /// so `nixos-install --flake` sees it (Nix ignores untracked files in a
    /// git tree). `configuration.nix` is immutable again on return.
    async fn run(&self, ctx: &TaskCtx, tx: &ProgressSink) -> mx::Result<()> {
        let mut added: Vec<&str> = Vec::new();

        if ctx.config.partitioning.encryption_enabled {
            let device = ctx.state.lock().await.luks_device.clone().ok_or_else(|| {
                mx::Error::Backend("encryption is enabled but no LUKS device was recorded".into())
            })?;
            let uuid = luks_uuid(&device).await?;
            write_file(
                LUKS_NIX,
                &luks_nix(&uuid, ctx.config.partitioning.tpm2_enabled),
            )
            .await?;
            added.push(LUKS_NIX);
            let _ = tx
                .send(ProgressEvent::Log(format!(
                    "recorded the LUKS root device {uuid} for the initrd"
                )))
                .await;
        }

        let packages = ctx.config.app_pack.packages(ctx.config.desktop_environment);
        if !packages.is_empty() {
            write_file(APPS_NIX, &apps_nix(&packages)).await?;
            added.push(APPS_NIX);
            let _ = tx
                .send(ProgressEvent::Log(format!(
                    "recorded {} application-pack packages",
                    packages.len()
                )))
                .await;
        }

        if added.is_empty() {
            return Ok(());
        }

        add_imports(&added).await?;
        git_commit("modulix installer: luks and application pack").await?;
        Ok(())
    }
}

/// Reads the UUID of a LUKS container, used to build a stable
/// `/dev/disk/by-uuid/…` reference for the initrd.
///
/// * `device` - the raw (pre-`luksOpen`) container, e.g. `/dev/sda2`.
///
/// # Returns
/// The container's UUID, without a trailing newline.
///
/// # Errors
/// `mx::Error::Backend` if `cryptsetup` cannot be run, exits non-zero, or
/// prints an empty UUID.
async fn luks_uuid(device: &str) -> mx::Result<String> {
    let output = tokio::process::Command::new("cryptsetup")
        .arg("luksUUID")
        .arg(device)
        .output()
        .await
        .map_err(|e| mx::Error::Backend(format!("cryptsetup could not be run: {e}")))?;
    if !output.status.success() {
        return Err(mx::Error::Backend(format!(
            "cryptsetup luksUUID {device} failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let uuid = String::from_utf8(output.stdout)?.trim().to_string();
    if uuid.is_empty() {
        return Err(mx::Error::Backend(format!(
            "cryptsetup luksUUID {device} returned nothing"
        )));
    }
    Ok(uuid)
}

/// Renders `luks.nix`.
///
/// * `uuid` - LUKS container UUID, referenced as `/dev/disk/by-uuid/…`.
/// * `tpm2` - whether `EnrollTpmTask` enrolled a TPM2 token, which decides
///   the `crypttabExtraOpts` needed for an automatic unlock.
///
/// # Returns
/// A NixOS module declaring the root container. `boot.initrd.systemd.enable`
/// is mandatory for a TPM2 unlock and harmless otherwise.
fn luks_nix(uuid: &str, tpm2: bool) -> String {
    let extra_opts = if tpm2 {
        "\n    crypttabExtraOpts = [ \"tpm2-device=auto\" ];"
    } else {
        ""
    };
    format!(
        r#"{{ config, lib, pkgs, ... }}:
{{
  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices."{LUKS_MAPPER_NAME}" = {{
    device = "/dev/disk/by-uuid/{uuid}";{extra_opts}
  }};
}}
"#
    )
}

/// Renders `apps.nix`.
///
/// * `packages` - nixpkgs attribute paths, e.g. `["firefox", "kdePackages.ark"]`.
///
/// # Returns
/// A NixOS module adding `packages` to `environment.systemPackages`.
fn apps_nix(packages: &[&str]) -> String {
    let list = packages
        .iter()
        .map(|p| format!("    {p}\n"))
        .collect::<String>();
    format!(
        r#"{{ config, lib, pkgs, ... }}:
{{
  environment.systemPackages = with pkgs; [
{list}  ];
}}
"#
    )
}

/// Writes one generated module into the configuration repository.
///
/// * `name` - file name relative to `CONFIG_REPO`.
/// * `content` - complete file content.
async fn write_file(name: &str, content: &str) -> mx::Result<()> {
    tokio::fs::write(format!("{CONFIG_REPO}/{name}"), content).await?;
    Ok(())
}

/// Appends file names to `configuration.nix`'s `imports` list.
///
/// * `names` - file names to import, each already written next to
///   `configuration.nix`.
///
/// # Pre-conditions
/// `configuration.nix` was rendered by `init::configuration_nix`, so it holds
/// exactly one `imports = [ … ];` block.
///
/// # Post-conditions
/// The file is immutable again, whether or not the edit succeeded.
///
/// # Errors
/// `mx::Error::Backend` if the `imports` block cannot be located, or if
/// `chattr` fails.
async fn add_imports(names: &[&str]) -> mx::Result<()> {
    let path = format!("{CONFIG_REPO}/{CONFIGURATION_NIX}");
    chattr("-i", &path).await?;

    let result = insert_imports(&path, names).await;

    // Re-seal even on failure: leaving the base configuration writable would
    // silently undo what `init` sealed.
    let sealed = chattr("+i", &path).await;
    result?;
    sealed
}

/// Rewrites `configuration.nix` with the extra imports. Split out of
/// [`add_imports`] so the immutable flag is restored on every path.
///
/// * `path` - absolute path to `configuration.nix`.
/// * `names` - file names to add to the `imports` list.
async fn insert_imports(path: &str, names: &[&str]) -> mx::Result<()> {
    let content = tokio::fs::read_to_string(path).await?;
    tokio::fs::write(path, with_extra_imports(&content, names)?).await?;
    Ok(())
}

/// Pure counterpart of [`insert_imports`]: returns `content` with `names`
/// appended to its `imports` list.
///
/// * `content` - the current `configuration.nix` source.
/// * `names` - file names to import, without the leading `./`.
///
/// # Errors
/// `mx::Error::Backend` if no `imports = [ … ];` block is found.
fn with_extra_imports(content: &str, names: &[&str]) -> mx::Result<String> {
    let open = content.find("imports = [").ok_or_else(|| {
        mx::Error::Backend("configuration.nix has no imports list to extend".into())
    })?;
    let close = content[open..]
        .find("];")
        .map(|i| open + i)
        .ok_or_else(|| {
            mx::Error::Backend("configuration.nix's imports list is unterminated".into())
        })?;

    let insert: String = names.iter().map(|n| format!("    ./{n}\n")).collect();
    let mut updated = String::with_capacity(content.len() + insert.len());
    updated.push_str(&content[..close]);
    updated.push_str(&insert);
    updated.push_str(&content[close..]);
    Ok(updated)
}

/// Flips a file's immutable flag.
///
/// * `flag` - `"-i"` to unseal, `"+i"` to seal.
/// * `path` - absolute path of the file.
async fn chattr(flag: &str, path: &str) -> mx::Result<()> {
    let output = tokio::process::Command::new("chattr")
        .arg(flag)
        .arg(path)
        .output()
        .await
        .map_err(|e| mx::Error::Backend(format!("chattr could not be run: {e}")))?;
    if !output.status.success() {
        return Err(mx::Error::Backend(format!(
            "chattr {flag} {path} failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    Ok(())
}

/// Stages and commits the whole configuration repository.
///
/// * `message` - commit message.
///
/// # Pre-conditions
/// `CONFIG_REPO` is a git repository (created by `init`).
///
/// # Post-conditions
/// Nothing is left untracked: `nixos-install --flake` reads the git tree and
/// would otherwise silently drop the files this task just wrote. The commit
/// identity is passed with `-c` so it does not depend on any global git
/// configuration, which a live ISO has none of.
async fn git_commit(message: &str) -> mx::Result<()> {
    git(&["add", "-A"]).await?;
    git(&[
        "-c",
        "user.name=Modulix Installer",
        "-c",
        "user.email=installer@modulix-os.local",
        "commit",
        "--no-gpg-sign",
        "-m",
        message,
    ])
    .await
}

/// Runs one `git` command inside the configuration repository.
///
/// * `args` - git arguments, appended after `-C CONFIG_REPO`.
async fn git(args: &[&str]) -> mx::Result<()> {
    let output = tokio::process::Command::new("git")
        .arg("-C")
        .arg(CONFIG_REPO)
        .args(args)
        .output()
        .await
        .map_err(|e| mx::Error::Backend(format!("git could not be run: {e}")))?;
    if !output.status.success() {
        return Err(mx::Error::Backend(format!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn luks_nix_adds_tpm2_options_only_when_enrolled() {
        let with_tpm = luks_nix("1234", true);
        assert!(with_tpm.contains("/dev/disk/by-uuid/1234"));
        assert!(with_tpm.contains("tpm2-device=auto"));
        assert!(with_tpm.contains("boot.initrd.systemd.enable = true;"));

        let without = luks_nix("1234", false);
        assert!(!without.contains("crypttabExtraOpts"));
    }

    #[test]
    fn extra_imports_land_inside_the_imports_list() {
        let source = "{ config, lib, pkgs, ... }:\n{\n  imports = [\n    ./fstab.nix\n  ];\n\n  networking.hostName = \"pc\";\n}\n";
        let updated = with_extra_imports(source, &["luks.nix", "apps.nix"]).unwrap();
        let imports_end = updated.find("];").unwrap();
        assert!(updated.find("./luks.nix").unwrap() < imports_end);
        assert!(updated.find("./apps.nix").unwrap() < imports_end);
        assert!(updated.contains("networking.hostName"));
    }

    #[test]
    fn extra_imports_reject_a_file_without_an_imports_list() {
        assert!(with_extra_imports("{ }\n", &["luks.nix"]).is_err());
    }

    #[test]
    fn apps_nix_lists_every_package() {
        let rendered = apps_nix(&["firefox", "kdePackages.ark"]);
        assert!(rendered.contains("with pkgs; ["));
        assert!(rendered.contains("    firefox\n"));
        assert!(rendered.contains("    kdePackages.ark\n"));
    }
}
